services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Extcode\CartProducts\:
    resource: '../Classes/*'

  Extcode\CartProducts\Domain\Finisher\Cart\AddToCartFinisher:
    public: true
